config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  #get '/help',            to: 'static_pages#help'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 
  # Index action to render all posts
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # New action for creating post
  def new
    @post = Post.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    if @post.save(post_params)
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    @post = Post.find(params[:id])
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # Update action updates the post with the new information
  def update
    @post = Post.find(params[:id])
    @post.category_id = params[:category_id]
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @post = Post.find(params[:id])
  end
  
  # The destroy action removes the post permanently from the database
  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to root_path
    else
      flash[:alert] = "Error updating post!"
    end
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :body, :description, :category_id)
  end
   
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
  this.shortname = "blog-standard";
  /* -> DELETE BEFORE USE, BUT THIS NEEDS TO BU UPDATED TO THIS FORMAT BEFORE GOING LIVE  this.page.url = "<%= url_for(host: ENV['APPLICATION_HOST']) %>"; */
  this.page.url = blog-standard-christianorourke.c9users.io
  this.page.identifier = 'post-<%= @post.id %>';
  this.page.title = '<%= @post.title %>';  
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://blog-standard.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<div class="center">
<%= simple_form_for @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <div class="form-group">
        <%= f.input :title, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.input :description, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select one!") %>
    </div>
    
    <div class="form-group">
        <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.button :submit %>
    </div>
<% end %>
</div>

app/views/posts/edit.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<h2>Edit Post</h2>

<%= render "posts/form" %>
</meta>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "posts/form" %>

app/views/posts/index.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center">
  <% @posts.each do |post| %>
      <h6>
        <%= post.created_at.strftime('%b %d, %Y') %></h6>
      </h6>
      <h3>
        <u><%= link_to "#{post.title}", post_path(post) %></u>
      </h3>
      <div class="center">
        <p>
          <%= truncate post.description, length: 300 %>
        </p>
      </div>

      <br>
  <% end %>
</div>
</meta>

app/views/posts/index.html.erb
<div class="center">
  <% @posts.each do |post| %>
      <h6>
        <%= post.created_at.strftime('%b %d, %Y') %></h6>
      </h6>
      <h3>
        <u><%= link_to "#{post.title}", post_path(post) %></u>
      </h3>
      <div class="center">
        <p>
          <%= truncate post.description, length: 300 %>
        </p>
      </div>

      <br>
  <% end %>
</div>

app/views/posts/new.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<h2>Create New Post</h2>
<% if logged_in? && current_user.admin? %> 
<%= render "posts/form" %>
<% else %>
<div class="center">
<h2><%= link_to "Log in to post", login_path %></h2>
</div>
<% end %>
</meta>

app/views/posts/new.html.erb
<h2>Create New Post</h2>
<% if logged_in? && current_user.admin? %> 
<%= render "posts/form" %>
<% else %>
<div class="center">
<h2><%= link_to "Log in to post", login_path %></h2>
</div>
<% end %>

app/views/posts/show.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
<div class="center">
  <h1><%= @post.title %></h1>
  <h5><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <p><%= raw @post.body %></p>
  <%= link_to "Return to Blog", root_path %>
  <% if logged_in? %>
    <p><%= link_to "Edit", edit_post_path(@post) %></p>
    <p><%= button_to 'Delete Post', @post, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
  <% end %>
  <%= render 'disqus' %>
</div>
</meta>

app/views/posts/show.html.erb
<div class="center">
  <h1><%= @post.title %></h1>
  <h5><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <p><%= raw @post.body %></p>
  <%= link_to "Return to Blog", root_path %>
  <% if logged_in? %>
    <p><%= link_to "Edit", edit_post_path(@post) %></p>
    <p><%= button_to 'Delete Post', @post, method: :delete, :onclick => "return confirm('Are you sure you want to delete this post?')" %></p>
  <% end %>
  <%= render 'disqus' %>
</div>