config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'posts#index'
  #get '/help',            to: 'static_pages#help'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  # Incase new users need to be created
  #get  '/signup',         to: 'users#new'
  #post '/signup',         to: 'users#create'
  resources :users
  resources :posts
  resources :categories
end

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% if flash.any? %>
        <% flash.keys.each do |flash_key| %>
          <% next if flash_key.to_s == 'timedout' %>
            <div class="alert-message <%= flash_key %>">
            <a class="close" data-dismiss="alert" href="#"> x</a>
            <% flash.discard(flash_key) %>
            </div>
        <% end %>
      <% end %>

      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <% if logged_in? && current_user.admin? %>
            <%= render 'layouts/logged_in_header' %>
        <% end %>
        <div class="container" id="logo">Blog</div>
        <div class="container" id="logo-two">Sample Blog</div>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Categories", categories_path, id: "logo-three" %></li>
                <li><%= link_to "Home", root_path, id: "logo-four" %></li>
                <li><%= link_to "Posts", posts_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_insta_button.html.erb
<style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-32 { width: 32px; height: 32px; background: url(//badges.instagram.com/static/images/ig-badge-sprite-32.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-32 { background-image: url(//badges.instagram.com/static/images/ig-badge-sprite-32@2x.png); background-size: 60px 178px; } }</style>
<a href="https://www.instagram.com/metaphysically8/?ref=badge" class="ig-b- ig-b-32"><img src="//badges.instagram.com/static/images/ig-badge-32.png" alt="Instagram" /></a>

app/views/layouts/_logged_in_header.html.erb
<div><%= link_to "Log out", logout_path, method: "delete", id: "header-side-logo" %></div>
<div><%= link_to "New Post", new_post_path, id: "header-side-logo" %></div>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
        <% if logged_in? && current_user.admin? %>
            <%= render 'layouts/logged_in_header' %>
        <% end %>
        <div class="container" id="logo">Blog</div>
        <div class="container" id="logo-two">Sample Blog</div>
    </div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Categories", categories_path, id: "logo-three" %></li>
                <li><%= link_to "Home", root_path, id: "logo-four" %></li>
                <li><%= link_to "Posts", posts_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </body>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="column col-xs-3" id="sidebar">
        <div class="sidebar-nav-fixed pull-right affix">    
                <ul class="nav">
                    <div class="center">
                    <ul><h5>Categories</h5></ul>
                    <% @categories = Category.all.order(created_at: :desc) %>
                    <% @categories.each do |category| %>
                        <ul id="p-side">
                            <%= link_to "#{category.name}", category_path(category) %> 
                        </ul>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true" aria-expanded="false">
                                <ul id="p-side">New Category</ul>
                            </button>
                            <div class="dropdown-menu"  aria-labelledby="dropdownMenuButton">
                                <% @category = Category.new %>
                                <%= simple_form_for(@category) do |f| %>
                                <p class="center"><%= f.error_notification %></p>
                                <p class="center"><%= f.input :name %></p>
                                <p class="center"><%= f.button :submit %></p>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                    </div>
                </ul>
        </div>    
</div>

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/phone_header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
      
  </head>
  <%= render 'layouts/sidebar' %>
    <body>
      <%= render 'layouts/application_layout' %>
    </body>
</html>